# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-16 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_meetup_meetup_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='start_time',
            field=models.TimeField(null=True, verbose_name=b'Start Time'),
        ),
    ]
