# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-05-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_meetup_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='time',
        ),
        migrations.RemoveField(
            model_name='requestmeetup',
            name='time',
        ),
        migrations.AddField(
            model_name='requestmeetup',
            name='end_time',
            field=models.TimeField(null=True, verbose_name=b'End Time'),
        ),
        migrations.AddField(
            model_name='requestmeetup',
            name='start_time',
            field=models.TimeField(null=True, verbose_name=b'Start Time'),
        ),
    ]
